#!/bin/bash

source .env   # Load DB credentials from .env

echo "Setting up PostgreSQL database '${DATABASE_NAME}' and user '${DATABASE_USER}'..."

sudo -u postgres psql << EOF
CREATE DATABASE ${DATABASE_NAME};
CREATE USER ${DATABASE_USER} WITH PASSWORD '${DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE ${DATABASE_NAME} TO ${DATABASE_USER};
\c ${DATABASE_NAME}
GRANT CREATE ON SCHEMA public TO ${DATABASE_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DATABASE_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DATABASE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DATABASE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${DATABASE_USER};
EOF
echo "Database setup complete!"